[package]
name = "rchess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

pleco = "0.5.0"
rand = "0.8.4"
text_io = "0.1.1"
rayon = "1.5.1"